### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by mitraazari** [T16APP/riskGameApp#13]
![usecases02](https://user-images.githubusercontent.com/32073496/31797380-0568a48a-b4fc-11e7-87e7-0323b709ae36.png)
![usecases01](https://user-images.githubusercontent.com/32073496/31797376-ffaf3874-b4fb-11e7-8e65-f6cb9a54e1b0.jpg)

**Comment by mitraazari** [comment]
The final version Usecases

**Comment by RanjuShetty** [comment]
Done and updated in Design document.
